### PR TITLE
Update Mocha and Chai to apply Mocha fix, specify Coffeescript compiler as a dev dependency.

### PR DESCRIPTION
**Pull request by d4goxn**
Applies the fix from https://github.com/mochajs/mocha/pull/1287

Also, add node_modules to .gitignore

### CODE REVIEW

**Comment by falsecz** [comment]
Thank you.

**Comment by d4goxn** [comment]
No probs, thanks for creating the module! I am considering using it for handling update conflicts in CouchDB. If I do do that, then I will have to modify it to throw an error or call an error handler for cases where manual intervention is required.

I have a test for that case in an [unresolvable-merge-conflict](https://github.com/d4goxn/3-way-merge/tree/unresolvable-merge-conflict) branch, but no solution yet.

**Comment by markgithub3** [comment]
@d4goxn Hi! Is this what you had in mind (unresolvable conflict)? https://github.com/falsecz/3-way-merge/commit/b148a61

**Comment by d4goxn** [comment]
That test of mine is no longer valid if this module no longer merges anything but objects - I see one of the changes is to throw an error if the inputs are not objects, whereas previously, it would merge strings and arrays as well.

An impossible object merge might look like:

```
original = {x: "o"}
a = {x: "a"}
b = {x: "b"}
```

I wish I could be more helpful, but work is crazy right now.

**Comment by markgithub3** [comment]
The example posted by you is perfectly mergeable, it actually returns `{x: "b"}`.
(See README.md: "When a conflict is detected (changes made in both version 2 and 3) changes from version 3 are used.")

 It only throws error when you call the function itself with non-object parameters

**Comment by d4goxn** [comment]
That is the defined behaviour, ok. As long as parameters are passed in chronological order, this gives us last-write-wins semantics, which is simple and useful for things like realtime collaborative editing. I was expecting git-like behaviour, where both branches are considered equal, and if there is more than one possible solution, then the user is given a merge conflict to resolve.

Last-write-wins actually is the type of resolution that works best for what I am working on.

**Pull request merged**
